export const foodList = [
  "Spaghetti Bolognese",
  "BicMac Rolle",
  "Hotdog Rolle",
  "Gschlagene mit Kartoffelbrei und Soße",
  "Quarkbällchen",
  "Disney Land Spezialität",
  "Pfannkuchen mit Hackfleisch",
  "Süße Pfannkuchen",
  "Pfannkuchen mit Schinken / Mais",
  "Apfelküchle",
  "Schnitzel mit Pommes (Ranken) / Gschlagene",
  "Salat vom Ranken",
  "Pat Thai Eriskirch",
  "Pat Thai Bahnschiene",
  "Pizza TT",
  "Wurstsalat",
  "Halb & Halb oder Ganz & Ganz",
  "Salat mit Reichenauer",
  "Ei im Glaß",
  "Hackbraten mit Kartoffelbrei",
  "Eier in Senfsoße",
  "Sandwiches",
  "Hot-Dogs",
  "Hamburger",
  "Döner Kaufland",
  "Kaufland Türke",
  "La Scala Pizza",
  "Mc Donalds",
  "Burger King",
  "Snack Teller",
  "Vespern"

];
